# workflow name
name: Publish

# on events
on:
  push:
    branches: ["master"]

# jobs
jobs:
  build:
    name: Build
    uses: ./.github/workflows/docker-build.yml
    with:
      app-name: android-sms-gateway-docs
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Initialize Terraform
        working-directory: deployments/
        run: terraform init

      - name: Deploy Docker service to Swarm
        working-directory: deployments/
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
          terraform apply -auto-approve -input=false \
          -var 'swarm-manager-host=${{ secrets.SWARM_MANAGER_HOST }}' \
          -var 'app-name=${{ vars.APP_NAME }}' \
          -var "app-version=${{ needs.build.outputs.app-version }}" \
          -var 'app-host=${{ vars.APP_HOST }}'
